name="sing-lang"
version="0.1.0-alpha.1"
entry="examples/hello.sg"
s="examples/hello.sg"
s="examples/dot.sg"
s="examples/vec.sg"
s="examples/div.sg"
s="examples/web.sg"
s="stdlib/core.sg"
s="stdlib/io.sg"
s="stdlib/math.sg"
s="stdlib/mem.sg"
s="stdlib/fs.sg"
s="stdlib/time.sg"
s="stdlib/test.sg"
s="stdlib/c.sg"
